export const CURRENCIES_NAMES
    : { [key: string]: string } = {
    EUR: 'Euro',
    USD: 'US Dollar',
    JPY: 'Japanese Yen',
    BGN: 'Bulgarian Lev',
    CZK: 'Czech Republic Koruna',
    DKK: 'Danish Krone',
    GBP: 'British Pound Sterling',
    HUF: 'Hungarian Forint',
    PLN: 'Polish Zloty',
    RON: 'Romanian Leu',
    SEK: 'Swedish Krona',
    CHF: 'Swiss Franc',
    ISK: 'Icelandic Króna',
    NOK: 'Norwegian Krone',
    HRK: 'Croatian Kuna',
    RUB: 'Russian Ruble',
    TRY: 'Turkish Lira',
    AUD: 'Australian Dollar',
    BRL: 'Brazilian Real',
    CAD: 'Canadian Dollar',
    CNY: 'Chinese Yuan',
    HKD: 'Hong Kong Dollar',
    IDR: 'Indonesian Rupiah',
    ILS: 'Israeli New Sheqel',
    INR: 'Indian Rupee',
    KRW: 'South Korean Won',
    MXN: 'Mexican Peso',
    MYR: 'Malaysian Ringgit',
    NZD: 'New Zealand Dollar',
    PHP: 'Philippine Peso',
    SGD: 'Singapore Dollar',
    THB: 'Thai Baht',
    ZAR: 'South African Rand',
}

export const CURRENCIES_SIGNS: { [key: string]: string } = {
    EUR: 'EUR',
    USD: 'USD',
    JPY: 'JPY',
    BGN: 'BGN',
    CZK: 'CZK',
    DKK: 'DKK',
    GBP: 'GBP',
    HUF: 'HUF',
    PLN: 'PLN',
    RON: 'RON',
    SEK: 'SEK',
    CHF: 'CHF',
    ISK: 'ISK',
    NOK: 'NOK',
    HRK: 'HRK',
    RUB: 'RUB',
    TRY: 'TRY',
    AUD: 'AUD',
    BRL: 'BRL',
    CAD: 'CAD',
    CNY: 'CNY',
    HKD: 'HKD',
    IDR: 'IDR',
    ILS: 'ILS',
    INR: 'INR',
    KRW: 'KRW',
    MXN: 'MXN',
    MYR: 'MYR',
    NZD: 'NZD',
    PHP: 'PHP',
    SGD: 'SGD',
    THB: 'THB',
    ZAR: 'ZAR',
}